// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcpP9xI5edJujQ_zfMEnTLQn11a92yIws',
    appId: '1:719601960728:web:05678b8b4930d5e19c406d',
    messagingSenderId: '719601960728',
    projectId: 'smart-kitchen-8c465',
    authDomain: 'smart-kitchen-8c465.firebaseapp.com',
    storageBucket: 'smart-kitchen-8c465.firebasestorage.app',
    measurementId: 'G-MFV6JD3YCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPEfWuL3wVMH_TrsEJvAtgP8-qIgwTjzg',
    appId: '1:719601960728:android:11ffda1ec2b9fed69c406d',
    messagingSenderId: '719601960728',
    projectId: 'smart-kitchen-8c465',
    storageBucket: 'smart-kitchen-8c465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhWmiCMgzpMXPL_BqhZyDk0FPHzvtTI5k',
    appId: '1:719601960728:ios:6f2d06212a87bd649c406d',
    messagingSenderId: '719601960728',
    projectId: 'smart-kitchen-8c465',
    storageBucket: 'smart-kitchen-8c465.firebasestorage.app',
    iosBundleId: 'com.example.smartKitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhWmiCMgzpMXPL_BqhZyDk0FPHzvtTI5k',
    appId: '1:719601960728:ios:6f2d06212a87bd649c406d',
    messagingSenderId: '719601960728',
    projectId: 'smart-kitchen-8c465',
    storageBucket: 'smart-kitchen-8c465.firebasestorage.app',
    iosBundleId: 'com.example.smartKitchen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcpP9xI5edJujQ_zfMEnTLQn11a92yIws',
    appId: '1:719601960728:web:c1a5a206d2d672809c406d',
    messagingSenderId: '719601960728',
    projectId: 'smart-kitchen-8c465',
    authDomain: 'smart-kitchen-8c465.firebaseapp.com',
    storageBucket: 'smart-kitchen-8c465.firebasestorage.app',
    measurementId: 'G-9KSE7TSBN7',
  );

}